//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arepa.Parser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arepa.Parser.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have selected the XML documentation file as output in your test project! - Have you selected the right project? - The project {0} does not have XML documentation  associated.
        /// </summary>
        internal static string StringErrorDocumentationFileNotFoundInProjectFile {
            get {
                return ResourceManager.GetString("StringErrorDocumentationFileNotFoundInProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file was not found!.
        /// </summary>
        internal static string StringErrorFileNotFound {
            get {
                return ResourceManager.GetString("StringErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments! Please enter: Arepa.exe -ProjectDir &lt;Test Project Directory&gt; -TestDir &lt;Test directory where the reports are located&gt;.
        /// </summary>
        internal static string StringErrorInvalidArguments {
            get {
                return ResourceManager.GetString("StringErrorInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one feature in your test project to continue! - Ensure you have selected the test project before run Arepa - Are you missing the @Feature: key? - No features were found on {0}.
        /// </summary>
        internal static string StringErrorNoFeaturesFound {
            get {
                return ResourceManager.GetString("StringErrorNoFeaturesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you missing the @Feature: key? - The scenario {0} does not have feature associated!.
        /// </summary>
        internal static string StringErrorNoFeaturesFoundForScenario {
            get {
                return ResourceManager.GetString("StringErrorNoFeaturesFoundForScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered the right test directory name or you have run the test at least once! - No MSTest file found at {0} .
        /// </summary>
        internal static string StringErrorNoMSTestFileFound {
            get {
                return ResourceManager.GetString("StringErrorNoMSTestFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered the right project directory name - No project file found at {0}.
        /// </summary>
        internal static string StringErrorNoProjectFileFound {
            get {
                return ResourceManager.GetString("StringErrorNoProjectFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scenario description was found in the scenario &lt;{0}&gt; on method {1}!.
        /// </summary>
        internal static string StringErrorNoScenarioDescriptionOnMethod {
            get {
                return ResourceManager.GetString("StringErrorNoScenarioDescriptionOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you missing the @Scenario: key? - No scenarios were found in the feature &lt;{0}&gt; on class {1}!.
        /// </summary>
        internal static string StringErrorNoScenariosOnFeature {
            get {
                return ResourceManager.GetString("StringErrorNoScenariosOnFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test results where found in the test report {0} for any scenario defined in the documentation file {1}.
        /// </summary>
        internal static string StringErrorNoTestResultsFound {
            get {
                return ResourceManager.GetString("StringErrorNoTestResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title was found in the feature on class {0}!.
        /// </summary>
        internal static string StringErrorNoTitleFoundOnFeature {
            get {
                return ResourceManager.GetString("StringErrorNoTitleFoundOnFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title was found in the scenario on method {0}!.
        /// </summary>
        internal static string StringErrorNoTitleOnScenario {
            get {
                return ResourceManager.GetString("StringErrorNoTitleOnScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user story was found in the feature on class {0}!.
        /// </summary>
        internal static string StringErrorNoUserStoryOnFeature {
            get {
                return ResourceManager.GetString("StringErrorNoUserStoryOnFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hummmm the report template for the scenario or the feature or the test report was not found!.
        /// </summary>
        internal static string StringErrorReportTemplateNotFound {
            get {
                return ResourceManager.GetString("StringErrorReportTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Arepa {0} finished at {1} - Total execution time {2} ==========.
        /// </summary>
        internal static string StringFinishingMessage {
            get {
                return ResourceManager.GetString("StringFinishingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, no errors or suggestions were found in your test project. All good!.
        /// </summary>
        internal static string StringInformationNoErrorOrSuggestion {
            get {
                return ResourceManager.GetString("StringInformationNoErrorOrSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arepa report was successfully generated at {0}.
        /// </summary>
        internal static string StringInformationReportGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("StringInformationReportGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description not found!.
        /// </summary>
        internal static string StringReportDefaultDescription {
            get {
                return ResourceManager.GetString("StringReportDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string StringReportNo {
            get {
                return ResourceManager.GetString("StringReportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string StringReportYes {
            get {
                return ResourceManager.GetString("StringReportYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Arepa {0} started at {1} ==========.
        /// </summary>
        internal static string StringStartingMessage {
            get {
                return ResourceManager.GetString("StringStartingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string StringTemplateError {
            get {
                return ResourceManager.GetString("StringTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arepa -&gt; {0}.
        /// </summary>
        internal static string StringTemplateInformation {
            get {
                return ResourceManager.GetString("StringTemplateInformation", resourceCulture);
            }
        }
    }
}
